name: Make Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: "zip"
        path: "./sign-bank/"
        filename: "SgSL Sign Bank.zip"
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SgSL Sign Bank.zip"
        commit: "main"
        tag: "v0.0.3"
